### ISSUE TITLE
Maven Central Jar Compiled with Java 1.8?

### ISSUE THREAD

**Issue by KAllan357** [awslabs/amazon-sqs-java-extended-client-lib#27]
When I switch my application to use the latest `1.0.1` version of this jar and pull it from Maven Central, I get the following exception:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/amazon/sqs/javamessaging/ExtendedClientConfiguration : Unsupported major.minor version 52.0, compiling:(/tmp/form-init8767020834767061108.clj:1:73)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.UnsupportedClassVersionError: com/amazon/sqs/javamessaging/ExtendedClientConfiguration : Unsupported major.minor version 52.0
```

I see in the pom.xml the compiler plugin is set to use Java 1.7 - is it possible though that the jar pushed to Maven Central was built incorrectly? 

For what it's worth, if I clone this repo and build it using my 1.7 JDK, I stop experiencing the error.

Thanks!

**Comment by jonwilks** [comment]
This got me too. Viewing bytes 7-8 of a class file associated w/ this jar shows '34 03' hexadecimal which I believe maps to java 8 per https://en.wikipedia.org/wiki/Java_class_file#General_layout
